[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req

[req_distinguished_name]

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = mars.int.bozza.au
DNS.2 = mars
IP.1 = 192.168.22.1
IP.2 = 124.187.49.228